-- Sprout analytics foundation. Expand-only and safe for mixed-version deploys.
begin;

create extension if not exists pgcrypto;

create table if not exists public.app_events (
    id bigint generated by default as identity primary key,
    user_id bigint,
    event_name text not null,
    event_source text not null,
    entity_type text,
    entity_id text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.app_events
    add column if not exists event_id uuid not null default gen_random_uuid(),
    add column if not exists session_id text;

create unique index if not exists app_events_event_id_idx
    on public.app_events (event_id);
create index if not exists app_events_name_created_idx
    on public.app_events (event_name, created_at desc);
create index if not exists app_events_user_created_idx
    on public.app_events (user_id, created_at desc);
create index if not exists app_events_source_created_idx
    on public.app_events (event_source, created_at desc);
create index if not exists app_events_entity_idx
    on public.app_events (entity_type, entity_id, created_at desc);

alter table public.app_events enable row level security;

-- Service-role writers and admin readers use the backend. No public policy is
-- intentionally created for raw analytics events.
commit;
