-- Collections: personal named lists + (Phase 2) group-backed collections.
-- Additive and idempotent.
begin;

-- ── collections ───────────────────────────────────────────────────────────────
create table if not exists public.collections (
    id              bigint generated by default as identity primary key,
    name            text not null,
    emoji           text not null default '📍',
    description     text,
    owner_user_id   bigint not null references public.users(id) on delete cascade,
    is_public       boolean not null default false,
    -- Phase 2: set when collection is backed by a Telegram group chat
    telegram_group_id bigint unique,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists collections_owner_idx
    on public.collections (owner_user_id, created_at desc);

-- ── collection_members ────────────────────────────────────────────────────────
-- Owner is always inserted here with role='owner' on collection creation.
create table if not exists public.collection_members (
    collection_id   bigint not null references public.collections(id) on delete cascade,
    user_id         bigint not null references public.users(id) on delete cascade,
    role            text not null default 'editor'
                        check (role in ('owner', 'editor')),
    invited_by      bigint references public.users(id) on delete set null,
    joined_at       timestamptz not null default now(),
    primary key (collection_id, user_id)
);

create index if not exists collection_members_user_idx
    on public.collection_members (user_id);

-- ── collection_places ─────────────────────────────────────────────────────────
-- Links existing places to a collection (filter/tag, not a copy).
-- place_id is nullable so Phase-2 group places (owned by another user) can be
-- referenced by google_place_id + denormalised fields instead.
create table if not exists public.collection_places (
    id              bigint generated by default as identity primary key,
    collection_id   bigint not null references public.collections(id) on delete cascade,
    place_id        bigint references public.places(id) on delete set null,
    -- Denormalised for display + map rendering
    google_place_id text,
    name            text not null,
    address         text,
    latitude        double precision,
    longitude       double precision,
    place_types     text,
    place_rating    double precision,
    added_by_user_id bigint not null references public.users(id),
    created_at      timestamptz not null default now(),
    -- A place (by google_place_id) can only appear once per collection
    unique (collection_id, google_place_id)
);

create index if not exists collection_places_collection_idx
    on public.collection_places (collection_id, created_at desc);
create index if not exists collection_places_place_idx
    on public.collection_places (place_id);
create index if not exists collection_places_user_idx
    on public.collection_places (added_by_user_id);

-- ── RLS ───────────────────────────────────────────────────────────────────────
-- Mini App uses service_role key (bypasses RLS).
-- RLS blocks direct anon/authenticated access.
alter table public.collections enable row level security;
alter table public.collection_members enable row level security;
alter table public.collection_places enable row level security;

-- service_role can do everything (no policy needed — it bypasses RLS).
-- Deny all for anon / authenticated by default (no permissive policies added).

commit;
