-- Capture enough context to diagnose every terminal link-processing failure.
-- Safe to run whether or not the original failed_extractions table already exists.
begin;

create table if not exists public.failed_extractions (
    id bigint generated by default as identity primary key,
    user_id bigint,
    url text not null,
    platform text not null default 'other',
    caption_preview text,
    reason text not null default 'no_slots',
    created_at timestamptz not null default now()
);

alter table public.failed_extractions
    add column if not exists failure_stage text not null default 'extraction',
    add column if not exists flow text not null default 'private',
    add column if not exists error_message text,
    add column if not exists request_id text,
    add column if not exists details jsonb not null default '{}'::jsonb;

create index if not exists failed_extractions_created_at_idx
    on public.failed_extractions (created_at desc);

create index if not exists failed_extractions_reason_idx
    on public.failed_extractions (reason, created_at desc);

create index if not exists failed_extractions_platform_idx
    on public.failed_extractions (platform, created_at desc);

alter table public.failed_extractions enable row level security;

-- Bot/admin API use the service role. No public table policy is intentionally created.
commit;
