-- Normalized social-content attribution and admin creator outcome analytics.
-- Additive and idempotent: legacy places.source_* columns remain authoritative fallback data.
begin;

create table if not exists public.content_sources (
    id bigint generated by default as identity primary key,
    platform text not null check (platform in ('instagram', 'tiktok', 'unknown')),
    platform_content_id text,
    canonical_url text not null,
    original_url text,
    source_account text,
    title text,
    caption_preview text,
    hashtags text[] not null default '{}',
    duration_seconds integer,
    thumbnail_url text,
    metadata_source text,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (platform, canonical_url)
);

create unique index if not exists content_sources_platform_id_uidx
    on public.content_sources (platform, platform_content_id)
    where platform_content_id is not null;
create index if not exists content_sources_account_idx
    on public.content_sources (platform, source_account);

create table if not exists public.content_attributions (
    id bigint generated by default as identity primary key,
    content_source_id bigint not null references public.content_sources(id) on delete cascade,
    user_id bigint not null,
    restaurant_key text not null,
    google_place_id text,
    place_id bigint references public.places(id) on delete set null,
    attribution_type text not null default 'new_save'
        check (attribution_type in ('new_save', 'rediscovery')),
    new_save_count integer not null default 0,
    rediscovery_count integer not null default 0,
    first_attributed_at timestamptz not null default now(),
    last_attributed_at timestamptz not null default now(),
    attribution_count integer not null default 1,
    request_id text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (content_source_id, user_id, restaurant_key)
);

create index if not exists content_attributions_restaurant_idx
    on public.content_attributions (restaurant_key, last_attributed_at desc);
create index if not exists content_attributions_source_idx
    on public.content_attributions (content_source_id, last_attributed_at desc);
create index if not exists content_attributions_user_restaurant_idx
    on public.content_attributions (user_id, restaurant_key, last_attributed_at desc);

alter table public.content_sources enable row level security;
alter table public.content_attributions enable row level security;

create or replace function public.content_platform_id(p_platform text, p_url text)
returns text language sql immutable parallel safe as $$
    select case
        when lower(coalesce(p_platform, '')) = 'instagram' then
            substring(p_url from '(?i)instagram\.com/(?:reel|p|tv)/([^/?#]+)')
        when lower(coalesce(p_platform, '')) = 'tiktok' then
            substring(p_url from '(?i)tiktok\.com/.*/video/([0-9]+)')
        else null
    end;
$$;

create or replace function public.canonical_content_url(p_platform text, p_url text)
returns text language sql immutable parallel safe as $$
    select case
        when public.content_platform_id(p_platform, p_url) is not null
             and lower(p_platform) = 'instagram'
            then 'https://www.instagram.com/reel/' || public.content_platform_id(p_platform, p_url) || '/'
        when public.content_platform_id(p_platform, p_url) is not null
             and lower(p_platform) = 'tiktok'
            then 'https://www.tiktok.com/video/' || public.content_platform_id(p_platform, p_url)
        else split_part(btrim(p_url), '?', 1)
    end;
$$;

create or replace function public.record_content_attribution(
    p_platform text,
    p_platform_content_id text,
    p_canonical_url text,
    p_original_url text,
    p_source_account text,
    p_title text,
    p_caption_preview text,
    p_hashtags text,
    p_duration_seconds integer,
    p_user_id bigint,
    p_place_id bigint,
    p_google_place_id text,
    p_restaurant_name text,
    p_restaurant_address text,
    p_attribution_type text,
    p_request_id text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_source_id bigint;
    v_restaurant_key text;
    v_attribution public.content_attributions;
begin
    if p_platform not in ('instagram', 'tiktok') or nullif(btrim(p_canonical_url), '') is null then
        return null;
    end if;

    select id into v_source_id
    from public.content_sources
    where platform = p_platform
      and (
          (p_platform_content_id is not null and platform_content_id = p_platform_content_id)
          or canonical_url = p_canonical_url
      )
    order by (platform_content_id = p_platform_content_id) desc nulls last
    limit 1;

    if v_source_id is null then
        insert into public.content_sources (
            platform, platform_content_id, canonical_url, original_url, source_account,
            title, caption_preview, hashtags, duration_seconds, metadata_source
        ) values (
            p_platform, p_platform_content_id, p_canonical_url, p_original_url,
            nullif(lower(ltrim(btrim(coalesce(p_source_account, '')), '@')), ''),
            nullif(p_title, ''), left(nullif(p_caption_preview, ''), 500),
            case when nullif(p_hashtags, '') is null then '{}'::text[]
                 else string_to_array(p_hashtags, ',') end,
            p_duration_seconds, 'runtime'
        )
        on conflict (platform, canonical_url) do update set
            platform_content_id = coalesce(content_sources.platform_content_id, excluded.platform_content_id),
            original_url = coalesce(content_sources.original_url, excluded.original_url),
            source_account = coalesce(content_sources.source_account, excluded.source_account),
            title = coalesce(content_sources.title, excluded.title),
            caption_preview = coalesce(content_sources.caption_preview, excluded.caption_preview),
            hashtags = case when cardinality(content_sources.hashtags) = 0 then excluded.hashtags else content_sources.hashtags end,
            duration_seconds = coalesce(content_sources.duration_seconds, excluded.duration_seconds),
            last_seen_at = now(), updated_at = now()
        returning id into v_source_id;
    else
        update public.content_sources set
            original_url = coalesce(original_url, p_original_url),
            source_account = coalesce(source_account, nullif(lower(ltrim(btrim(coalesce(p_source_account, '')), '@')), '')),
            title = coalesce(title, nullif(p_title, '')),
            caption_preview = coalesce(caption_preview, left(nullif(p_caption_preview, ''), 500)),
            duration_seconds = coalesce(duration_seconds, p_duration_seconds),
            last_seen_at = now(), updated_at = now()
        where id = v_source_id;
    end if;

    v_restaurant_key := public.admin_restaurant_key(p_google_place_id, p_restaurant_name, p_restaurant_address);
    insert into public.content_attributions (
        content_source_id, user_id, restaurant_key, google_place_id, place_id,
        attribution_type, new_save_count, rediscovery_count, request_id
    ) values (
        v_source_id, p_user_id, v_restaurant_key, p_google_place_id, p_place_id,
        p_attribution_type,
        case when p_attribution_type = 'new_save' then 1 else 0 end,
        case when p_attribution_type = 'rediscovery' then 1 else 0 end,
        p_request_id
    )
    on conflict (content_source_id, user_id, restaurant_key) do update set
        google_place_id = coalesce(content_attributions.google_place_id, excluded.google_place_id),
        place_id = coalesce(excluded.place_id, content_attributions.place_id),
        attribution_type = case when content_attributions.new_save_count > 0 or excluded.new_save_count > 0 then 'new_save' else 'rediscovery' end,
        new_save_count = content_attributions.new_save_count + excluded.new_save_count,
        rediscovery_count = content_attributions.rediscovery_count + excluded.rediscovery_count,
        last_attributed_at = now(),
        attribution_count = content_attributions.attribution_count + 1,
        request_id = coalesce(excluded.request_id, content_attributions.request_id),
        updated_at = now()
    returning * into v_attribution;

    return jsonb_build_object(
        'content_source_id', v_source_id,
        'attribution_id', v_attribution.id,
        'type', p_attribution_type
    );
end;
$$;

-- Idempotent historical backfill from the source metadata already stored on places.
insert into public.content_sources (
    platform, platform_content_id, canonical_url, original_url, source_account,
    title, caption_preview, hashtags, duration_seconds, metadata_source,
    first_seen_at, last_seen_at
)
select
    lower(p.source_platform),
    max(public.content_platform_id(lower(p.source_platform), p.source_url)),
    public.canonical_content_url(lower(p.source_platform), p.source_url),
    (array_agg(p.source_url order by p.created_at))[1],
    max(nullif(lower(ltrim(p.source_uploader, '@')), '')),
    max(nullif(p.source_title, '')),
    left(max(nullif(p.source_title, '')), 500),
    coalesce(string_to_array(max(nullif(p.source_hashtags, '')), ','), '{}'::text[]),
    max(p.source_duration),
    'legacy_places',
    min(p.created_at),
    max(p.created_at)
from public.places p
where p.source_url is not null
  and lower(coalesce(p.source_platform, '')) in ('instagram', 'tiktok')
group by lower(p.source_platform), public.canonical_content_url(lower(p.source_platform), p.source_url)
on conflict (platform, canonical_url) do update set
    platform_content_id = coalesce(content_sources.platform_content_id, excluded.platform_content_id),
    source_account = coalesce(content_sources.source_account, excluded.source_account),
    title = coalesce(content_sources.title, excluded.title),
    hashtags = case when cardinality(content_sources.hashtags) = 0 then excluded.hashtags else content_sources.hashtags end,
    duration_seconds = coalesce(content_sources.duration_seconds, excluded.duration_seconds),
    first_seen_at = least(content_sources.first_seen_at, excluded.first_seen_at),
    last_seen_at = greatest(content_sources.last_seen_at, excluded.last_seen_at),
    updated_at = now();

insert into public.content_attributions (
    content_source_id, user_id, restaurant_key, google_place_id, place_id,
    attribution_type, new_save_count, rediscovery_count,
    first_attributed_at, last_attributed_at, attribution_count, request_id
)
select
    cs.id, p.user_id,
    public.admin_restaurant_key(p.google_place_id, p.name, p.address),
    p.google_place_id, p.id, 'new_save', 1, 0,
    p.created_at, p.created_at, 1, 'legacy-backfill:' || p.id::text
from public.places p
join public.content_sources cs
  on cs.platform = lower(p.source_platform)
 and cs.canonical_url = public.canonical_content_url(lower(p.source_platform), p.source_url)
where p.source_url is not null
  and lower(coalesce(p.source_platform, '')) in ('instagram', 'tiktok')
on conflict (content_source_id, user_id, restaurant_key) do nothing;

create or replace function public.admin_content_outcomes()
returns table (
    attribution_id bigint, content_source_id bigint, platform text, canonical_url text,
    source_account text, title text, duration_seconds integer, user_id bigint,
    restaurant_key text, google_place_id text, place_id bigint, restaurant_name text,
    city text, cuisine text, new_save_count integer, rediscovery_count integer,
    first_attributed_at timestamptz, last_attributed_at timestamptz,
    attributed_visit boolean, visited_at timestamptz, review_id bigint,
    sentiment text, food_score numeric, vibe_score numeric, value_score numeric,
    review_score numeric, reviewed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
with base as (
    select
        ca.*, cs.platform, cs.canonical_url, cs.source_account, cs.title, cs.duration_seconds,
        p.name restaurant_name, p.city, p.primary_cuisine cuisine, p.visited_at,
        (p.is_visited is true and p.visited_at is not null
         and p.visited_at >= ca.first_attributed_at
         and p.visited_at < ca.last_attributed_at + interval '90 days') qualifies_visit
    from public.content_attributions ca
    join public.content_sources cs on cs.id = ca.content_source_id
    left join public.places p on p.id = ca.place_id
),
visit_candidates as (
    select b.id,
        row_number() over (
            partition by b.user_id, b.restaurant_key
            order by b.last_attributed_at desc, b.id desc
        ) visit_rank
    from base b where b.qualifies_visit
),
enriched as (
    select b.*, coalesce(vc.visit_rank = 1, false) attributed_visit
    from base b left join visit_candidates vc on vc.id = b.id
)
select
    e.id, e.content_source_id, e.platform, e.canonical_url, e.source_account, e.title,
    e.duration_seconds, e.user_id, e.restaurant_key, e.google_place_id, e.place_id,
    e.restaurant_name, e.city, e.cuisine, e.new_save_count, e.rediscovery_count,
    e.first_attributed_at, e.last_attributed_at, e.attributed_visit, e.visited_at,
    case when e.attributed_visit then r.id::bigint end,
    case when e.attributed_visit then r.sentiment end,
    case when e.attributed_visit then r.food_score::numeric end,
    case when e.attributed_visit then r.vibe_score::numeric end,
    case when e.attributed_visit then r.value_score::numeric end,
    case when e.attributed_visit then public.sprout_review_score(r.food_score, r.vibe_score, r.value_score, r.sentiment, r.overall_rating) end,
    case when e.attributed_visit then coalesce(r.updated_at, r.created_at) end
from enriched e
left join lateral (
    select rr.* from public.reviews rr
    where rr.place_id = e.place_id and rr.user_id = e.user_id and rr.is_public is true
      and coalesce(rr.updated_at, rr.created_at) >= e.first_attributed_at
    order by coalesce(rr.updated_at, rr.created_at) desc, rr.id desc limit 1
) r on true;
$$;

create or replace function public.admin_content_posts(
    p_platform text default null, p_account text default null, p_city text default null,
    p_cuisine text default null, p_start timestamptz default null, p_end timestamptz default null,
    p_sort text default 'saves', p_limit integer default 50, p_offset integer default 0
) returns table (
    content_source_id bigint, platform text, canonical_url text, source_account text, title text,
    duration_seconds integer, new_saves bigint, rediscoveries bigint, unique_users bigint,
    restaurant_count bigint, visits bigint, reviews bigint, loved_rate numeric,
    adjusted_score numeric, content_format text, last_attributed_at timestamptz, total_count bigint
)
language sql security definer set search_path = public as $$
with filtered as (
    select * from public.admin_content_outcomes() o
    where (p_platform is null or o.platform = p_platform)
      and (p_account is null or o.source_account ilike '%' || p_account || '%')
      and (p_city is null or lower(coalesce(o.city,'')) = lower(p_city))
      and (p_cuisine is null or lower(coalesce(o.cuisine,'')) = lower(p_cuisine))
      and (p_start is null or o.first_attributed_at >= p_start)
      and (p_end is null or o.first_attributed_at < p_end)
), agg as (
    select f.content_source_id, max(f.platform) platform, max(f.canonical_url) canonical_url,
        max(f.source_account) source_account, max(f.title) title, max(f.duration_seconds) duration_seconds,
        sum(f.new_save_count)::bigint new_saves, sum(f.rediscovery_count)::bigint rediscoveries,
        count(distinct f.user_id) unique_users, count(distinct f.restaurant_key) restaurant_count,
        count(distinct f.user_id) filter (where f.attributed_visit) visits,
        count(distinct f.user_id) filter (where f.review_id is not null) reviews,
        round(100.0 * count(*) filter (where f.review_id is not null and f.sentiment='loved') / nullif(count(*) filter (where f.review_id is not null),0),1) loved_rate,
        avg(f.review_score) raw_score, max(f.last_attributed_at) last_attributed_at
    from filtered f group by f.content_source_id
), scored as (
    select a.*,
        case when a.raw_score is null then null else round(((a.reviews*a.raw_score)+(5*6.0))/(a.reviews+5),2) end adjusted_score,
        case when a.restaurant_count > 1 then 'roundup' else 'single_restaurant' end content_format,
        count(*) over() total_count
    from agg a
)
select s.content_source_id,s.platform,s.canonical_url,s.source_account,s.title,s.duration_seconds,
    s.new_saves,s.rediscoveries,s.unique_users,s.restaurant_count,s.visits,s.reviews,
    coalesce(s.loved_rate,0),s.adjusted_score,s.content_format,s.last_attributed_at,s.total_count
from scored s
order by
    case when p_sort='visits' then s.visits end desc,
    case when p_sort='reviews' then s.reviews end desc,
    case when p_sort='score' then s.adjusted_score end desc nulls last,
    case when p_sort='recent' then s.last_attributed_at end desc,
    case when p_sort not in ('visits','reviews','score','recent') then s.new_saves end desc,
    s.unique_users desc, s.content_source_id
limit least(greatest(p_limit,1),100) offset greatest(p_offset,0);
$$;

create or replace function public.admin_source_accounts(
    p_platform text default null, p_search text default null, p_start timestamptz default null,
    p_end timestamptz default null, p_sort text default 'saves', p_limit integer default 50,
    p_offset integer default 0
) returns table (
    platform text, source_account text, post_count bigint, new_saves bigint,
    rediscoveries bigint, unique_users bigint, restaurant_count bigint, visits bigint,
    reviews bigint, loved_rate numeric, adjusted_score numeric, last_attributed_at timestamptz,
    total_count bigint
)
language sql security definer set search_path = public as $$
with f as (
    select * from public.admin_content_outcomes() o
    where (p_platform is null or o.platform=p_platform)
      and (p_search is null or coalesce(o.source_account,'unknown') ilike '%'||p_search||'%')
      and (p_start is null or o.first_attributed_at>=p_start)
      and (p_end is null or o.first_attributed_at<p_end)
), a as (
    select max(f.platform) platform, coalesce(f.source_account,'unknown') source_account,
        count(distinct f.content_source_id) post_count, sum(f.new_save_count)::bigint new_saves,
        sum(f.rediscovery_count)::bigint rediscoveries, count(distinct f.user_id) unique_users,
        count(distinct f.restaurant_key) restaurant_count,
        count(distinct f.user_id) filter(where f.attributed_visit) visits,
        count(distinct f.user_id) filter(where f.review_id is not null) reviews,
        round(100.0*count(*) filter(where f.review_id is not null and f.sentiment='loved')/nullif(count(*) filter(where f.review_id is not null),0),1) loved_rate,
        avg(f.review_score) raw_score, max(f.last_attributed_at) last_attributed_at
    from f group by f.platform, coalesce(f.source_account,'unknown')
), s as (
    select a.*, case when raw_score is null then null else round(((reviews*raw_score)+(5*6.0))/(reviews+5),2) end adjusted_score,
        count(*) over() total_count from a
)
select s.platform,s.source_account,s.post_count,s.new_saves,s.rediscoveries,s.unique_users,
    s.restaurant_count,s.visits,s.reviews,coalesce(s.loved_rate,0),s.adjusted_score,
    s.last_attributed_at,s.total_count
from s order by
    case when p_sort='visits' then s.visits end desc,
    case when p_sort='reviews' then s.reviews end desc,
    case when p_sort='score' then s.adjusted_score end desc nulls last,
    case when p_sort not in ('visits','reviews','score') then s.new_saves end desc,
    s.unique_users desc,s.source_account
limit least(greatest(p_limit,1),100) offset greatest(p_offset,0);
$$;

create or replace function public.admin_restaurant_content_sources(
    p_restaurant_key text, p_limit integer default 20, p_offset integer default 0
) returns table (
    content_source_id bigint, platform text, canonical_url text, source_account text, title text,
    new_saves bigint, rediscoveries bigint, unique_users bigint, visits bigint, reviews bigint,
    loved_rate numeric, adjusted_score numeric, last_attributed_at timestamptz, total_count bigint
)
language sql security definer set search_path=public as $$
with a as (
    select o.content_source_id,max(o.platform) platform,max(o.canonical_url) canonical_url,
        max(o.source_account) source_account,max(o.title) title,sum(o.new_save_count)::bigint new_saves,
        sum(o.rediscovery_count)::bigint rediscoveries,count(distinct o.user_id) unique_users,
        count(distinct o.user_id) filter(where o.attributed_visit) visits,
        count(distinct o.user_id) filter(where o.review_id is not null) reviews,
        round(100.0*count(*) filter(where o.review_id is not null and o.sentiment='loved')/nullif(count(*) filter(where o.review_id is not null),0),1) loved_rate,
        avg(o.review_score) raw_score,max(o.last_attributed_at) last_attributed_at
    from public.admin_content_outcomes() o where o.restaurant_key=p_restaurant_key group by o.content_source_id
),s as (
    select a.*,case when raw_score is null then null else round(((reviews*raw_score)+(5*6.0))/(reviews+5),2) end adjusted_score,
        count(*) over() total_count from a
)
select s.content_source_id,s.platform,s.canonical_url,s.source_account,s.title,s.new_saves,
    s.rediscoveries,s.unique_users,s.visits,s.reviews,coalesce(s.loved_rate,0),s.adjusted_score,
    s.last_attributed_at,s.total_count
from s order by s.new_saves desc,s.unique_users desc,s.last_attributed_at desc
limit least(greatest(p_limit,1),100) offset greatest(p_offset,0);
$$;

create or replace function public.admin_content_post_detail(p_content_source_id bigint)
returns jsonb language sql security definer set search_path=public as $$
with o as (select * from public.admin_content_outcomes() where content_source_id=p_content_source_id),
r as (
    select restaurant_key,max(restaurant_name) name,max(city) city,max(cuisine) cuisine,
        sum(new_save_count) new_saves,count(distinct user_id) unique_users,
        count(distinct user_id) filter(where attributed_visit) visits,
        count(distinct user_id) filter(where review_id is not null) reviews,
        round(100.0*count(*) filter(where review_id is not null and sentiment='loved')/nullif(count(*) filter(where review_id is not null),0),1) loved_rate
    from o group by restaurant_key
), metrics as (
    select sum(new_save_count) new_saves,sum(rediscovery_count) rediscoveries,
        count(distinct user_id) unique_users,count(distinct restaurant_key) restaurant_count,
        count(distinct user_id) filter(where attributed_visit) visits,
        count(distinct user_id) filter(where review_id is not null) reviews,
        round(100.0*count(*) filter(where review_id is not null and sentiment='loved')/nullif(count(*) filter(where review_id is not null),0),1) loved_rate,
        avg(review_score) raw_score,min(first_attributed_at) first_attributed_at,max(last_attributed_at) last_attributed_at from o
)
select jsonb_build_object(
    'id',cs.id,'platform',cs.platform,'canonical_url',cs.canonical_url,'source_account',cs.source_account,
    'title',cs.title,'caption_preview',cs.caption_preview,'hashtags',cs.hashtags,'duration_seconds',cs.duration_seconds,
    'new_saves',m.new_saves,'rediscoveries',m.rediscoveries,'unique_users',m.unique_users,
    'restaurant_count',m.restaurant_count,'visits',m.visits,'reviews',m.reviews,
    'loved_rate',coalesce(m.loved_rate,0),'adjusted_score',case when m.raw_score is null then null else round(((m.reviews*m.raw_score)+(5*6.0))/(m.reviews+5),2) end,
    'first_attributed_at',m.first_attributed_at,'last_attributed_at',m.last_attributed_at,
    'restaurants',coalesce((select jsonb_agg(to_jsonb(r) order by r.new_saves desc) from r),'[]'::jsonb)
)
from public.content_sources cs cross join metrics m where cs.id=p_content_source_id;
$$;

revoke all on table public.content_sources, public.content_attributions from public, anon, authenticated;
grant all on table public.content_sources, public.content_attributions to service_role;
grant usage, select on sequence public.content_sources_id_seq, public.content_attributions_id_seq to service_role;
revoke all on function public.record_content_attribution(text,text,text,text,text,text,text,text,integer,bigint,bigint,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.admin_content_outcomes() from public,anon,authenticated;
revoke all on function public.admin_content_posts(text,text,text,text,timestamptz,timestamptz,text,integer,integer) from public,anon,authenticated;
revoke all on function public.admin_source_accounts(text,text,timestamptz,timestamptz,text,integer,integer) from public,anon,authenticated;
revoke all on function public.admin_restaurant_content_sources(text,integer,integer) from public,anon,authenticated;
revoke all on function public.admin_content_post_detail(bigint) from public,anon,authenticated;
grant execute on function public.record_content_attribution(text,text,text,text,text,text,text,text,integer,bigint,bigint,text,text,text,text,text) to service_role;
grant execute on function public.admin_content_outcomes() to service_role;
grant execute on function public.admin_content_posts(text,text,text,text,timestamptz,timestamptz,text,integer,integer) to service_role;
grant execute on function public.admin_source_accounts(text,text,timestamptz,timestamptz,text,integer,integer) to service_role;
grant execute on function public.admin_restaurant_content_sources(text,integer,integer) to service_role;
grant execute on function public.admin_content_post_detail(bigint) to service_role;

commit;
